[project]
name = "openllm-ocr-annotator"
version = "0.1.0"
description = "Multimodal OCR annotation tool using multiple LLM APIs."
readme = "README.md"
requires-python = ">=3.13.2"
license = { text = "MIT" }
authors = [
  { name = "Loong Ma", email = "diqiuzhuanzhuan@gmail.com" }
]
dependencies = [
  "openai",
  "requests",
  "pillow",
  "pyyaml",
  "tqdm"
]

[project.urls]
homepage = "https://github.com/diqiuzhuanzhuan/openllm-ocr-annotator"
repository = "https://github.com/diqiuzhuanzhuan/openllm-ocr-annotator"

[tool.uv]
virtualenvs.in-project = true

[project.optional-dependencies]
dev = ["black", "isort", "pytest"]
