openai:
  api_key: "your-api-key"
  model: "gpt-4-vision-preview"

qwen:
  api_key: "your-api-key"
  model: "qwen-vl-plus"

gemini:
  api_key: "your-api-key"
  model: "gemini-pro-vision"

claude:
  api_key: "your-api-key"
  model: "claude-3-opus"

mistral:
  endpoint: "http://your-mistral-api"
  model: "mistral-large"

grok:
  api_key: "your-api-key"
  model: "grok-1"
