version: "1.0"

variables:
  document_type: "document"
  field_type: "text"
  field_name: "content"
  fields_to_extract: |
    - Title: The main title or header
    - Content: The main body text
    - Date: Any dates found in the document
    - Reference: Any reference numbers or IDs
  example_prompt: |
    Example: For a receipt or invoice, extract the total amount, date, and items purchased.
    You will return the results in the following JSON format:
    {
      "fields": [
        {
          "field_name": "total_amount",
          "value": "extracted value",
          "position": {"x": 0, "y": 0, "width": 100, "height": 50},
          "confidence": 0.91,
          "type": "text"
        },
        {
          "field_name": "date",
          "value": "extracted value",
          "position": {"x": 0, "y": 0, "width": 100, "height": 50},
          "confidence": 0.92,
          "type": "text"
        },
        {
          "field_name": "items",
          "value": "extracted value",
          "position": {"x": 0, "y": 0, "width": 100, "height": 50},
          "confidence": 0.95,
          "type": "text"
        }
      ],
      "metadata": {
        "document_type": "receipt",
        "quality_score": 0.95,
        "language": "english"
      }
    }

default:
  vision_extraction:
    system: |
        You are an expert in {{document_type}} information extraction. 
        Focus on extracting information from {{document_type}} images with high accuracy.
        Return the results in the following JSON format:
        {
          "fields": [
            {
              "field_name": "{{field_name}}",
              "value": "extracted value",
              "position": {"x": 0, "y": 0, "width": 100, "height": 50},
              "confidence": 0.95,
              "type": "{{field_type}}"
            }
          ],
          "metadata": {
            "document_type": "{{document_type}}",
            "quality_score": 0.95,
            "language": "detected language"
          }
        }
    user: |
      Please extract the following fields from this {{document_type}}:
      {{fields_to_extract}}
      {{example_prompt}}
      Return in the specified JSON format.

  ocr:
    system: |
      You are an expert OCR annotator. Please analyze the image and extract all text content.
      Return the results in the following JSON format:
      {
        "text_blocks": [
          {
            "text": "detected text",
            "position": {"x": 0, "y": 0, "width": 100, "height": 50},
            "confidence": 0.95,
            "type": "text|title|table|list"
          }
        ]
      }
    user: "Please extract all text from this image with their locations and return in the specified JSON format."
  
  layout:
    system: |
      You are an expert document layout analyzer. Identify all document elements including:
      - Headers and titles
      - Paragraphs
      - Tables
      - Lists
      - Images and figures
      Return the results in JSON format.
    user: "Please analyze this document's layout and identify all structural elements."

# Model specific templates - will override default if specified
openai:
  vision_extraction:
    system: |
      You are an expert in foreign trade document analysis. Your task is to extract key information 
      from Chinese foreign trade documents with high precision. Pay special attention to:
      1. Document identifiers and numbers
      2. Dates in standard formats
      3. Company names and addresses
      4. Transaction amounts and currencies
      5. Geographic information

    user: |
      Analyze this foreign trade document and extract the following specific fields:

      Required Fields:
      1. Document Number
         - Format: Any alphanumeric identifier EXACTLY as shown in the document
         - Example: "CONTRACT-2024-001" or "FT20240101"
         - Note: Do not modify or normalize the number
         - Use "N/A" if no clear document number is found or if it's partially illegible
      
      2. Contract Date
         - Format: yyyy-mm-dd
         - Example: "2024-01-01"
      
      3. Buyer's Name
         - Format: Full company/entity name
         - Example: "ABC Trading Company Ltd."
         - Note: As much as possible keep the original name.
      
      4. Buyer's Country/Region
         - Format: Three-letter country code (ISO 3166-1 alpha-3)
         - Example: "USA" for United States, "GBR" for United Kingdom
         - Note: Infer from address or contact details if not explicitly stated
      
      5. Transaction Amount
         - Format: Number with 2 decimal places + three-letter currency code
         - Example: "123,44.50 USD" or "987,446.54 EUR"

      Important Rules for Missing or Unclear Information:
      1. Missing Values:
         - ALWAYS use exactly "N/A" (not "NA", "n/a", "null", or empty string)
         - Do not try to guess or infer values if you are not highly confident
         - Example: If no document number is found, use "N/A"
      
      2. Partial Information:
         - If only part of the information is available, use "N/A" rather than incomplete data
         - Example: If date is "2024-xx-xx", use "N/A" instead of partial date
      
      3. Unclear or Ambiguous Values:
         - When multiple possible values exist, use "N/A" rather than guessing
         - When text is illegible or unclear, use "N/A"
      
      4. Confidence Scores:
         - Use 0.99 for clear, directly stated values
         - Use 0.85-0.95 for inferred values (e.g., country codes from addresses)
         - Use 0.50 when returning "N/A" due to missing/unclear information
      
      5. Additional Guidelines:
         - For country codes: only use ISO 3166-1 alpha-3, otherwise use "N/A"
         - For currency codes: only use ISO 4217, otherwise use "N/A"
         - For dates: only use yyyy-mm-dd format, otherwise use "N/A"
      
      Return the results in this exact JSON format:
      {
        "fields": [
          {
            "field_name": "document_number",
            "value": "CONTRACT-2024-001",
            "confidence": 0.99
          },
          {
            "field_name": "contract_date", 
            "value": "N/A",
            "confidence": 0.50
          },
          {
            "field_name": "buyer_name",
            "value": "ABC Trading Company Ltd.",
            "confidence": 0.99
          },
          {
            "field_name": "buyer_country",
            "value": "USA",
            "confidence": 0.85
          },
          {
            "field_name": "transaction_amount",
            "value": "123,456.00 USD",
            "confidence": 0.99
          }
        ],
        "metadata": {
          "document_type": "foreign_trade",
          "language": "English"
        }
      }

      
  ocr:
    system: |
      You are an expert OCR annotator using GPT-4V. Please analyze the image and extract all text content.
      Return the results in the following JSON format:
      {
        "text_blocks": [
          {
            "text": "detected text",
            "position": {"x": 0, "y": 0, "width": 100, "height": 50},
            "confidence": 0.95,
            "type": "text|title|table|list"
          }
        ]
      }
    user: "Please extract all text from this image with their locations and return in the specified JSON format."